---
- name: Obtener la IP del servidor
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Mostrar la IP del servidor
      debug:
        msg: "La dirección IP del servidor es {{ ansible_default_ipv4.address }}"
