---
- name: Obtener la IP del servidor
  hosts: all
  gather_facts: yes
  tasks:
    - name: Mostrar la IP del servidor
      debug:
        msg: "La dirección IP del servidor es {{ ansible_all_ipv4_addresses }}"
